In [12]:
#pip install pandas

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("employee_performance.csv")
df

,ExperienceYears,WorkHoursPerWeek,SkillScore,ProjectsHandled,TrainingHours,PerformanceScore
0,6,49,5,13,19,65.388163
1,19,57,5,10,0,79.942743
2,14,40,6,4,71,85.082437
3,10,33,7,5,86,94.611649
4,7,44,1,5,62,45.695157
...,...,...,...,...,...,...
795,7,46,5,11,9,70.227323
796,4,55,6,14,52,69.131499
797,3,32,5,6,43,67.913331
798,5,53,7,5,46,56.695633
799,1,35,2,8,52,48.182347

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ExperienceYears   800 non-null    int64
 1   WorkHoursPerWeek  800 non-null    int64
 2   SkillScore        800 non-null    int64
 3   ProjectsHandled   800 non-null    int64
 4   TrainingHours     800 non-null    int64
 5   PerformanceScore  800 non-null    float64
dtypes: float64(1), int64(5)
memory usage: 37.6 KB

In [16]:
df.isnull().sum()

ExperienceYears     0
WorkHoursPerWeek    0
SkillScore          0
ProjectsHandled     0
TrainingHours       0
PerformanceScore    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.describe()

,ExperienceYears,WorkHoursPerWeek,SkillScore,ProjectsHandled,TrainingHours,PerformanceScore
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,9.240000,44.443750,5.396250,6.870000,48.563750,70.251711
std,5.944247,8.750574,2.860851,4.225271,27.918233,23.320799
min,0.000000,30.000000,1.000000,0.000000,0.000000,0.000000
25%,4.000000,37.000000,3.000000,3.000000,25.000000,54.750318
50%,9.000000,44.000000,5.000000,7.000000,47.000000,71.035083
75%,15.000000,52.000000,8.000000,11.000000,72.000000,90.588846
max,19.000000,59.000000,10.000000,14.000000,99.000000,100.000000

In [19]:
x=df.drop(['PerformanceScore'],axis=1)
y=df['PerformanceScore']

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42
                                               )

In [21]:
#from sklearn.tree import DecisionTreeRegressor #SCORE:0.7501
#from sklearn.ensemble import RandomForestRegressor #SCORE:8930
from sklearn.linear_model import LinearRegression #SCORE:0.9253
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9401288300719901

In [22]:
import pickle
with open('employee.pkl','wb') as f:
    pickle.dump(model,f)